name: Instagram Reddit Automator
on:
    workflow_dispatch: 
    schedule:
        # Every 6 hours
        - cron: '0 */6 * * *'  # You can change the time here
        
jobs:
    upload:
        runs-on: ubuntu-latest
        env:
            INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
            INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
            SUBREDDIT: ${{ secrets.SUBREDDIT }}
            UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
            UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
            SENTRY_URL: ${{ secrets.SENTRY_URL }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  
            - name: Run script
              run: python main.py


    